# Códigos dos municípios

Diversos SIS apresentam códigos representanto os municípios de residência do usuário e de local de atendimento do evento de saúde. Os códigos dos municípios são criados e mantidos pelo IBGE.

Os códigos gerados pelo IBGE contêm 7 digitos: os dois primeiros remetem à Unidade da Federação (UF) e os quatro digitos seguintes identificam o município, enquanto o último (sétimo) dígito, é um código verificador.

::::: {.callout}
Os SIS costumam apresentar os códigos dos municípios com apenas os primeiros seis dígitos, omitindo o último dígito verificador.
:::

## Tabela de códigos

A tabela abaixo, gerada com ajuda do pacote [{geobr}](https://ipeagit.github.io/geobr/) [@geobr], apresenta os códigos dos municípios brasileiros. Você pode efetuar uma busca pelo nome do município usando a caixa 'Procurar'.

```{r}
#| message: false
#| echo: false
library(geobr)
library(sf)
library(dplyr)
library(DT)

mun <- read_municipal_seat() |>
  st_drop_geometry() |>
  mutate(code_muni = as.character(code_muni)) |>
  select(-c(code_state, code_region, year)) |>
  select(
    `Região` = name_region,
    `UF` = abbrev_state,
    `Município` = name_muni,
    `Código` = code_muni
  )

datatable(
  data = mun,
  rownames = FALSE,
  options = list(
    language = list(
      url = "https://cdn.datatables.net/plug-ins/1.10.11/i18n/Portuguese.json"
    )
  )
)
```

O projeto [IBGE Cidades](https://cidades.ibge.gov.br) também é uma ótima forma de consultar os códigos dos municípios.

## Criação de municípios e Divisão Territorial Brasileira

O IBGE é responsável pela Divisão Territorial Brasileira (DTB), mantendo um histórico sobre a criação, extinção e junção de municípios, alterasões de divisas e outras modificações da DTB.

Acesse a [página da DTB](https://www.ibge.gov.br/geociencias/organizacao-do-territorio/estrutura-territorial/23701-divisao-territorial-brasileira.html) para mais detalhes.