# Organização dos SIS

## Sistemas de Informação Vitais

O Brasil conta atualmente com dois sistemas de informação vitais, o Sistema de Informações sobre Mortalidade (SIM) e o Sistema de Informações sobre Nascidos Vivos (SINASC). A implantação destes sistemas se origina na reorganização do Registro Civil brasileiro, que visava padronizar os instrumentos de coleta de dados sobre óbitos e nascimentos e produzir dados de maneira uniforme em todo o território nacional.

## Sistemas de Informação de Morbidade

Existem atualmente dois sistemas de informação em saúde consolidados, que apresentam dados sobre a morbidade da população brasileira: o Sistema de Informações de Agravos de Notificação (SINAN) e o Sistema de Informações Hospitalares (SIH).

## Outros Sistemas de Informação

Além dos sistemas de informação em saúde descritos anteriormente, podem-se destacar alguns outros. O Sistema de Informações Ambulatoriais (SIA) abrange dados sobre atendimentos ambulatoriais, serviços de apoio diagnóstico e terapêutico, e ações de prevenção e promoção de saúde, cobrindo unidades de saúde da dimensão pública do SUS e rede conveniada. O Sistema de Informação do Programa Nacional de Imunização (SI-PNI) contempla dados sobre vacinação da população brasileira. O Sistema de Informações Sobre Orçamentos Públicos em Saúde (SIOPS), apresenta dados sobre orçamentos públicos e gastos em saúde. O Sistema de Vigilância Epidemiológica (SIVEP) apresenta subsistemas específicos para malária e gripe (Síndrome Respiratória Aguda Grave -- SRAG).

Além dos sistemas de informação em saúde, cabe também destacar a importância do Cadastro Nacional de Estabelecimentos de Saúde (CNES), que apresenta dados cadastrais sobre todos os estabelecimentos de saúde no território nacional, e de profissionais de saúde, equipamentos, serviços de apoio diagnóstico e terapêutico e serviços ambulatoriais e hospitalares.

## Dimensões pública e privada do SUS

Cabe aqui ressaltar que alguns SIS apresentam uma cobertura ampla, incluindo as dimensões pública e privada do SUS. Nestes SIS, todo evento de saúde é contabilizado, independente dele aconter em um estabelecimento de saúde público ou privado. Pode-se citar o SIM, SINASC e o SINAN como exemplos. Assim, qualquer óbito, nascimento ou possível caso de doença ou agravo de interesse ocorrido em território nacional é comunicado ao Ministério da Saúde e é registrado em seu respectivo SIS,

::::: {.callout}
O Sistema Único de Saúde (SUS) engloba todos os profissionais, estabelecimentos e serviços de saúde oferecidos no Brasil, independente de serem privados, públicos ou filantrópicos.

Na estrutura do SUS, os serviços *privados* de saúde, como atendimentos particulares, clínicas privadas e planos de saúde privados, são visto como uma estrutura de [Saúde Suplementar](https://www.gov.br/servidor/pt-br/acesso-a-informacao/faq/sou-gov.br/saude-suplementar/conceito-e-legislacao) aos serviços públicos de saúde e são regulamentados pela [Agência Nacional de Saúde Suplementar (ANS)](https://www.gov.br/ans/pt-br).
:::

Por outro lado, alguns SIS são restritos à dimensão pública do SUS. Neste caso, apenas eventos de saúde ocorridos em estabelecimentos de saúde públicos são registrados. SIH e SIA são exemplos de SIS com este tipo de cobertura. A ANS apresenta regularmente dados sobre eventos de saúde ocorridos na dimensão privada do SUS. 

## Doenças, agravos e SIS

É importante salientar que os diferentes SIS são organizados por **eventos de saúde** e não por doenças e agravos. Eventos de saúde são nascimentos, internações, atendimentos ambulatoriais, notificação de suspeita de doença, imunizações e óbitos, entre outros. 

Desta forma, ao se procurar por dados de uma determinada doença ou agravo, deve-se refletir como esta doença ou agravo irá se refletir nos diferentes sistemas de informação em saúde. Por exemplo, a doença "Dengue" pode se manifestar em diversos SIS: o caso suspeito é lançado no SINAN, se evoluir para internação hospitalar será lançado também no SIH, os procedimentos terapêuticos serão lançados no SIA e, caso venha a óbito, também constará no SIM.

Os capítulos seguintes irão apresentar estes e outros SIS brasileiros, com seu histórico e organização, estrutura dos seus dados, formas de acesso, seus principais usos e indicadores, bibliografia recomendada e outras informações relevantes.