# SISAB - Sistema de Informação em Saúde para a Atenção Básica

## Resumo

-  Ano de criação: 2013
-  Cobertura: Dimensão pública do SUS
-  Unidade: equipe, município, região de saúde, UF
-  Divulgação dos dados: mensal com até um mês de defasagem

## Histórico e organização

O SISAB é o sistema de informação da Atenção Básica vigente para fins de financiamento e de adesão aos programas e estratégias da Política Nacional de Atenção Básica, criado pela portaria GM/MS nº 1.412, de 10 de julho de 2013, substituindo o antigo Sistema de Informação da Atenção Básica (SIAB). 

O SISAB é parte integrante do Departamento de Saúde da Família (DESF/SAPS/MS), conectado aos sistemas da Atenção Primária (e-SUS APS), que permite a coleta e registro de dados com os seguinges subsistemas que são alimentados pelos municípios: 

-  Coleta de Dados Simplificado (CDS);

-  Prontuário Eletrônico do Cidadão (PEC) e

-  Aplicativos para dispositivos móveis, como o e-SUS Território e Atividade Coletiva.

Os sistemas e-SUS APS foram desenvolvidos para atender os processos de trabalho da Atenção Primária para a gestão do cuidado em saúde, podendo ser utilizado por profissionais de todas as equipes e unidades da APS, Atenção Domiciliar (AD), além dos profissionais que realizam ações no âmbito de programas como o Saúde na Escola (PSE) e a Academia da Saúde.

O SISAB permite obter informações da situação sanitária e de saúde da população do território por meio de relatórios de saúde e indicadores por estado, município, região de saúde e equipe.

## Estrutura dos dados

Os dados do SISAB são estruturados nas seguintes categorias:

-  Cadastros vinculados às equipes da Atenção Primária a Saúde (APS)
-  Pré-natal
-  Indicadores de desempenho e Indicador Sintético Final (ISF)
-  Produção, incluindo atendimentos individuais, atendimento odontológico, procedimentos e visitas domiciliares da APS
-  Atividades coletivas da APS 

## Acesso aos dados

O acesso aos dados do SISAB é realizado através da geração on-line de relatórios, não sendo possível o acesso aos microdados do sistema.

Os relatórios podem ser extraídos no seguinte endereço: [https://sisab.saude.gov.br](https://sisab.saude.gov.br)

## Bibliografia recomendada

### Artigos

-  Artigo *Atenção Básica e Informação: análise do Sistema de Informação em Saúde para Atenção Básica (SISAB) e estratégia e-SUS AB e suas repercussões para uma gestão da saúde com transparência.[trabalho de conclusão de curso]* [@soares2016atenccao]. Disponível [aqui](https://www.espp.pr.gov.br/sites/escola-saude/arquivos_restritos/files/migrados/File/SISAB.pdf).

### Vídeos

{{< video https://www.youtube.com/watch?v=Si4Q6Xy4JF4 >}}
